# Change these first
owner: FamilyFirstAPD
repo: ff-uptime

sites:
  - name: Family First
    url: https://familyfirst.net
  - name: All Pro Dad Chapters
    url: https://allprodadchapters.com
assignees: # Users to assign downtime issues (optional)
  - brianburridge
  - StephenSGambill
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: 
  baseUrl: /ff-uptime
  logoUrl: https://familyfirst.net/wp-content/themes/familyfirst/img/GroupLockup_FF-Stack-Color-230px.png
  name: Family First Uptime
  introTitle: "Family First Site Uptime Status"
  introMessage: This site shows the uptime status for the Family First public web sites.
  theme: dark
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
